auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/loki
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki
  storage_config:
    boltdb_shipper:
      active_index_directory: /tmp/loki/boltdb-shipper-active
      shared_store: filesystem
    filesystem:
      directory: /tmp/loki/chunks

schema_config:
  configs:
    - from: 2020-10-27
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

compactor:
  working_directory: /tmp/loki/compactor
  compaction_interval: 10m

query_range:
  align_queries_with_step: true
  cache_results: true
  max_query_lookback: 7d

query_scheduler:
  max_outstanding_requests: 500

frontend:
  max_outstanding_per_tenant: 200

querier:
  max_concurrent: 20
  query_timeout: 1m

analytics:
  reporting_enabled: false




