server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
  - job_name: monitron_app
    static_configs:
      - targets:
          - localhost
        labels:
          job: monitron_app
          __path__: /home/ubuntu/monitron/logs/app.log


